server:
  port: 10000

spring:
  profiles:
    active: dev

logging:
  file:
    path: logs/online_shopping_gateway
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 100MB
