spring:
  cloud:
    gateway:
      enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
      routes:
        - id: auth_module
          uri: lb://online-shopping-auth
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/?(?<segment>.*), /api/$\{segment}

server:
  port: 10001
