spring:
  redis:
    password: wdy707000
    client-type: lettuce
    cluster:
      nodes: 82.157.178.60:7000,82.157.178.60:7001,82.157.178.60:7002
      max-redirects: 3
    lettuce:
      pool:
        max-idle: 16
        min-idle: 1
        max-active: 16
        enabled: true
        max-wait: -1
      cluster:
        refresh:
          adaptive: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://82.157.178.60:3306/online_shopping?serverTimezone=GMT%2B8
    username: root
    password: wdy123
    druid:
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        # 禁用HTML页面上的reset all 功能
        reset-enable: false
        login-username: wdy
        login-password: 123456
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      filter:
        stat:
          db-type: mysql
          enabled: true
        wall:
          enabled: true
        slf4j:
          enabled: true
          connection-log-enabled: true
          connection-rollback-after-log-enabled: true
          connection-commit-after-log-enabled: true

aliyun:
  message:
    appcode: 68ca3f0d89e448f8999c1f90bb3c0dbb
    url: https://intlsms.market.alicloudapi.com/comms/sms/sendmsgall
jwt:
  jwt-secret: UWZSXNZA6M7ZCMCQPH89FRN3M7CD8V2FDAF5A75C497C418A90E5F4FB3A861CEB
  jwt-expiration-in-ms: 86400000

page:
  login-url: http://localhost